from . import db, state_db
from .afk_db import (
    AfkSetResult,
    check_cooldown,
    cleanup_cooldowns,
    delete_user_data,
    get_afk_user,
    get_afk_users,
    get_all_afk,
    get_expired_afk,
    get_user_stats,
    init_afk_db,
    mark_nick_applied,
    release_cooldown,
    remove_afk,
    reserve_cooldown,
    set_afk,
    set_cooldown,
    take_afk,
    update_stats_on_remove,
    update_stats_on_set,
)
from .db import metrics as db_metrics, shutdown as shutdown_db
from .migrations import LATEST_SCHEMA_VERSION, SchemaError, migrate_schema, schema_version
from .schema import (
    ACTIVE_STATUSES,
    ALL_STATUSES,
    STATUS_ACCEPTED,
    STATUS_CLOSED,
    STATUS_DENIED,
    STATUS_OPEN,
    STATUS_PROCESSING,
    TERMINAL_STATUSES,
)
from .tickets_db import (
    add_log_message_id,
    anonymize_user_tickets,
    begin_transition,
    delete_ticket,
    delete_ticket_by_id,
    finalize_transition,
    get_active_tickets,
    get_all_tickets,
    get_open_ticket_for_user,
    get_retention_expired,
    get_stale_processing,
    get_stats,
    get_ticket,
    get_ticket_by_id,
    get_user_tickets,
    init_db,
    parse_log_message_refs,
    release_transition,
    save_ticket,
    update_ticket_status,
)

__all__ = [
    # соединение и метрики
    "db",
    "db_metrics",
    "shutdown_db",
    # миграции и схема
    "LATEST_SCHEMA_VERSION",
    "SchemaError",
    "migrate_schema",
    "schema_version",
    "STATUS_OPEN",
    "STATUS_PROCESSING",
    "STATUS_ACCEPTED",
    "STATUS_DENIED",
    "STATUS_CLOSED",
    "ACTIVE_STATUSES",
    "TERMINAL_STATUSES",
    "ALL_STATUSES",
    # state_db
    "state_db",
    # tickets_db
    "init_db",
    "save_ticket",
    "get_ticket",
    "get_ticket_by_id",
    "get_open_ticket_for_user",
    "get_active_tickets",
    "get_stale_processing",
    "get_user_tickets",
    "delete_ticket",
    "delete_ticket_by_id",
    "begin_transition",
    "release_transition",
    "finalize_transition",
    "update_ticket_status",
    "get_stats",
    "get_all_tickets",
    "get_retention_expired",
    "anonymize_user_tickets",
    "add_log_message_id",
    "parse_log_message_refs",
    # afk_db
    "AfkSetResult",
    "init_afk_db",
    "set_afk",
    "take_afk",
    "remove_afk",
    "mark_nick_applied",
    "get_afk_user",
    "get_afk_users",
    "get_all_afk",
    "get_expired_afk",
    "check_cooldown",
    "reserve_cooldown",
    "release_cooldown",
    "set_cooldown",
    "cleanup_cooldowns",
    "get_user_stats",
    "update_stats_on_set",
    "update_stats_on_remove",
    "delete_user_data",
]
